### ISSUE TITLE
Thunderbird/Linux: broken icons in toolbar menu

### ISSUE THREAD

**Issue by mgieseki** [ChoGGi/CuteButtons#1]
CuteButtons works great with Thunderbird on Windows. On Linux (Fedora and Ubuntu 64 bit), there seems to be a bug somewhere as some icons in the toolbar menu show some random pixel pattern. All icons in the main menu bar look fine. Here are two screen shots showing the menu and CuteButtons settings dialog (version 0.5.4):

![menu-shot](https://cloud.githubusercontent.com/assets/3620467/24794505/3967c38e-1b86-11e7-9d36-0f5de7253bde.png)

![settings-shot](https://cloud.githubusercontent.com/assets/3620467/24795105/77b5ffaa-1b88-11e7-8484-2da5afab8901.png)

**Comment by ChoGGi** [comment]
Huh, not sure why it'd show the mosaic file, but I'll take a looksee. Newest version of TB?

**Comment by mgieseki** [comment]
Yes, I'm using the latest version of TB (52.0) but the issue already showed up in the 45.x releases.
Thanks for taking a look.

**Comment by ChoGGi** [comment]
Fixed it, you'll need to download
https://raw.githubusercontent.com/ChoGGi/CuteButtons/master/content/Icons.Hover.css
https://raw.githubusercontent.com/ChoGGi/CuteButtons/master/content/Icons.Normal.css
and replace the ones in
/home/USERNAME/.thunderbird/********.default/CuteButtonsSVG
then restart TB, or wait for 0.5.5

**Comment by mgieseki** [comment]
Great, it works. Thanks for the super quick fix!

**Comment by ChoGGi** [comment]
Your welcome.
