### ISSUE TITLE
Loading CuteButtons via UserChrome.css results in non-functional right-click menu after updating to FF68

### ISSUE THREAD

**Issue by Skyyblaze** [ChoGGi/CuteButtons#12]
Ever since I started using Firefox Quantum I had CuteButtons loaded via my UserChrome.css file, however after updating to Firefox Quantum 68 today loading CuteButtons that way results in any right-click menu being just a small, gray rectangle without any options.

I confirmed that the issue is CuteButtons because uncommenting

 `@import url("Icons.Normal.css");`

from my UserChrome and restarting Firefox fixes the issue. Am I missing something here or did FF68 break compatibility?

**Comment by ChoGGi** [comment]
I'm going to say this is somewhat the same issue as https://github.com/ChoGGi/CuteButtons/issues/11
