### ISSUE TITLE
CuteButtons and Adblock Plus

### ISSUE THREAD

**Issue by stonecrusher** [ChoGGi/CuteButtons#2]
Hi!
When looking at the Adblock Plus context menu, it is not visible if it is activated or deactivated for the whole domain. It should be shown with a red x or a green checkmark as for the other options.
See screenshots:

Without CuteButtons
![wo_cb](https://cloud.githubusercontent.com/assets/1388389/24865460/99326ffc-1e07-11e7-9e69-3ee36d32d637.png)

With CuteButtons
![with_cb](https://cloud.githubusercontent.com/assets/1388389/24865515/cf724bd2-1e07-11e7-99cd-339badf04677.png)

Windows 8.1 x64
Firefox 52.0.2 32-bit
CuteButtons 0.5.4
Adblock Plus 1.3.10
But it didn't pop up recently, I've had this issue as long as I can remember.

Anyway thanks for the addon,
stonecrusher

**Comment by ChoGGi** [comment]
Weird, not sure why that has a clear icon.

Anyways fixed it, you'll need to download
https://raw.githubusercontent.com/ChoGGi/CuteButtons/master/content/Icons.Hover.css
https://raw.githubusercontent.com/ChoGGi/CuteButtons/master/content/Icons.Normal.css
and replace the ones in
%APPDATA%\Mozilla\Firefox\Profiles\<profile folder>\CuteButtonsSVG
then restart FF, or wait for 0.5.5


I'd also like to add an icon for that Element zum Verestecken menuitem, but I can't see it in my install
BTW don't you get a bunch of errors or issues running such an old version of ABP?

**Comment by stonecrusher** [comment]
Thank you, the fix works well and you were blazing fast!
And you are right, I confused version number of ABP with version number of another addon "[ABP element hiding helper](https://addons.mozilla.org/en/firefox/addon/elemhidehelper/)". That is the addon that adds the extra item "Element zum Verstecken auswählen" (choose element to be hidden) in context menu.
My current ABP version is 2.8.2 which should be the current version.
