### ISSUE TITLE
CuteButtons additional buttons not working in FF 55.0.3

### ISSUE THREAD

**Issue by trumpy81** [ChoGGi/CuteButtons#3]
Unfortunately, In FF 55.0.3 all of the additional buttons that were displayed when customising FireFox are no longer shown.

I would really like to get those back as there were several buttons that I used and relied on.

I hope this is possible and I would like to thank you for all of your efforts in producing this great addon, I have used it for a long time now and I'm lost without it, thanks again.

**Comment by ChoGGi** [comment]
These buttons?
![firefox55buttons](https://user-images.githubusercontent.com/1261282/30517987-14c4fcf4-9b2e-11e7-840b-ea86c9ee320a.png)

**Comment by trumpy81** [comment]
Yes, the extra buttons that are added in that area. I see much the same as your screenshot, there are no extra buttons added there anymore. :(

**Comment by ChoGGi** [comment]
What do you mean by extra buttons?

**Comment by trumpy81** [comment]
In previous versions of FireFox there were loads of extra buttons shown in that screenshot. Shortcuts for eBay, Paypal, menus etc. but they are not shown now.

**Comment by ChoGGi** [comment]
What addon added those icons (or at least one of them)?

**Comment by trumpy81** [comment]
I believe it was CuteButtons?

At least those icons only appeared when I added CuteButtons. If I disabled CuteButtons, then the buttons/shortcuts would disappear.

**Comment by ChoGGi** [comment]
I'm just getting more confused :)
CB adds icons to buttons, it doesn't add buttons. What addon can I install to add some of these buttons that CB hides in the customise window?

**Comment by trumpy81** [comment]
These are the buttons I am referring to. I had to fire up an old VM to capture the image below just before Firefox synced and updated itself.

![ff buttons](https://user-images.githubusercontent.com/12381786/30519461-556bc812-9bda-11e7-8d7e-ee58d7ad2c95.png)

**Comment by ChoGGi** [comment]
So, "What addon can I install to add some of these buttons"?

**Comment by trumpy81** [comment]
So you are saying that CuteButtons - Crystal SVG does not add those buttons/shortcuts?

That seems odd to me since I have been using that for ages now and it is responsible for adding those buttons/shortcuts.

**Comment by ChoGGi** [comment]
CB just adds icons to buttons, you might be thinking of https://codefisher.org/toolbar_button/

**Comment by trumpy81** [comment]
No, I am referring to CuteButtons - Crystal SVG. I have never had Toolbar Buttons installed.

**Comment by ChoGGi** [comment]
Then I don't know where you got all those buttons from?

**Comment by trumpy81** [comment]
OK, well thanks for your time, I do appreciate it. I will keep searching.

**Comment by ChoGGi** [comment]
You could check your addons list for disabled addons, maybe you have some other addon that adds a bunch of buttons?

**Comment by trumpy81** [comment]
No, I have checked the list of apps, including disabled apps, but none effect the buttons as far as I can tell, other than CuteButtons.

Perhaps I have had an add-on, possibly toolbar buttons, in the past and it was kept by syncing from an older version of FF in one of my many VM's or simply cached in my sync data. I don't recall seeing it in my app list in recent times though.

**Comment by ChoGGi** [comment]
Well, I wish you luck in your search for the missing buttons.
