### ISSUE TITLE
subtle bug, waterfox fails to start

### ISSUE THREAD

**Issue by pirate486743186** [ChoGGi/CuteButtons#4]
The last version (0.5.5) brakes something, and my waterfox consistently can't start, unless i start in safe mode first, then restart as normal. And then if i try to restart it gets blocked at start up again..... No message.....

I'll test later what's exactly the problem. A clean profile with just cutebutons in it, doesn't do that.

I have a bunch of extension.... :/

**Comment by ChoGGi** [comment]
Got a list of extensions?

**Comment by pirate486743186** [comment]
beh... just forget it. :D
