### ISSUE TITLE
In FF 57, some icon viewing X

### ISSUE THREAD

**Issue by readingsnail** [ChoGGi/CuteButtons#6]
i using FF 57, and all content's all image file is put the folder, CuteButtons is working, but some problem is here

<img width="250" alt="2017-11-15 2 21 17" src="https://user-images.githubusercontent.com/1904967/32820177-61c71ec2-ca10-11e7-9a9b-3433bf4ad95b.png">
Firefox Main Menu

<img width="250" alt="2017-11-15 2 21 21" src="https://user-images.githubusercontent.com/1904967/32820174-61383522-ca10-11e7-955d-7e1fe87b0afc.png">
Edit Menu

<img width="217" alt="2017-11-15 2 21 26" src="https://user-images.githubusercontent.com/1904967/32820175-61697466-ca10-11e7-86f6-1d4651ccff43.png">
Tool Menu

<img width="257" alt="2017-11-15 2 21 29" src="https://user-images.githubusercontent.com/1904967/32820176-61998426-ca10-11e7-8b5f-8b751c68750f.png">
Web Tools

<img width="384" alt="2017-11-15 2 23 32" src="https://user-images.githubusercontent.com/1904967/32820223-92389f9a-ca10-11e7-88c8-aae884ae2474.png">
also Help menu

so my CSS setting is here. so what's happen & can i fix it to right icon?
<img width="802" alt="2017-11-15 2 24 53" src="https://user-images.githubusercontent.com/1904967/32820260-c28787b0-ca10-11e7-9daa-e21b9361d928.png">
<img width="802" alt="2017-11-15 2 24 50" src="https://user-images.githubusercontent.com/1904967/32820261-c2c1a6fc-ca10-11e7-8bf6-04deda8b0e80.png">

**Comment by ChoGGi** [comment]
You'll have to remove Icons.CheckmarkMenu.css/Icons.CheckmarkMenuHover.css
they don't work well with Firefox under OSX (for some reason almost every menuitem has a type=checkmark).

**Comment by readingsnail** [comment]
OK Thanks, it's solved
