### ISSUE TITLE
CB fails on checkboxes when importing address book

### ISSUE THREAD

**Issue by stonecrusher** [ChoGGi/CuteButtons#9]
Thunderbird 52.9.1 (32-Bit)
CuteButtons 0.5.6

Importing a .csv addressbook:
How it looks
![2018-08-13 00_14_08-adressbuch importieren](https://user-images.githubusercontent.com/1388389/44007020-4f285378-9e8e-11e8-84ab-55425f326219.png)

How it really is
![2018-08-13 00_15_11-adressbuch importieren](https://user-images.githubusercontent.com/1388389/44007021-4f4b3a1e-9e8e-11e8-89b0-82ee1d2898e3.png)

**Comment by ChoGGi** [comment]
Sorry, I didn't see this :)

Could you upload or link to an example address book file?

**Comment by ChoGGi** [comment]
Updated

**Comment by ChoGGi** [comment]
Updated
https://github.com/ChoGGi/CuteButtons/commit/9802d8bbee52fe9806a84d9e9b5f717202511f59

**Comment by stonecrusher** [comment]
Hmm, something is strange. The version from the Palemoon site doesn't work for me in TB 52.9.1
I can install it but no icons are added anywhere.

I guess it's just not the latest version 0.5.8 because it explicitly says 0.5.7 despite having modification date of today.

BUT when I reinstalled [0.5.6](https://addons.thunderbird.net/de/thunderbird/addon/cutebuttons-crystal-svg/) it also doesn't work anymore :-/

**Comment by ChoGGi** [comment]
Where do you see 0.5.8?

When you press ctrl-shift-j do you see any error msgs from cutebuttons show up?

**Comment by ChoGGi** [comment]
Yeah, that's on github, it isn't in a release.

I see the issue now though, thanks fixed
https://addons.palemoon.org/addon/cutebuttons/

**Comment by stonecrusher** [comment]
Thank you, now everything works as expected.
